### ISSUE TITLE
An exception on an RPC call causes the whole connection to fail

### ISSUE THREAD

**Issue by edsko** [well-typed/grapesy#102]
I _think_ that this is a limitation of `http2`, but I do not know for sure. One potential clue I found during debugging this is that perhaps things go wrong in `http2` is we throw an exception in `outboundTrailersMaker`, but I don't know if that is a red herring or not.

To reproduce this, change `clientGlobal` in `Test.Driver.Dialogue.Execution` to always use a single connection, and plenty of test cases will start to fail.

**Comment by edsko** [comment]
It's conceivable that #187 fixed this.

**Comment by edsko** [comment]
It's looking like this might have swung to the other extreme. In `demo-client.md` , section "Automatic reconnect", we describe what should happen to a streaming connection when the server disappears (we expect the call to fail). However, this is not actually happening (anymore?). Instead, we get

```
demo-client: KilledByHttp2ThreadManager (Just ConnectionIsTimeout)
```

This happens whether or not the server is restarted in the meantime.

**Comment by FinleyMcIlwaine** [comment]
I'm seeing that this change in behavior was introduced by #183. At that commit ([41b5f2aae727c011921976b68b69e200d9565bba](https://github.com/well-typed/grapesy/commit/41b5f2aae727c011921976b68b69e200d9565bba)) the demo client started failing with `KilledByHttp2ThreadManager` rather than `CallClosedWithoutTrailers` when the server disappears on a streaming connection.
