### ISSUE TITLE
Should treat absence of grpc-encoding header as identity

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [well-typed/grapesy#69]
While testing against the go implementation with `--deflate` on the demo-client, the client succeeded even though the server did not compress the response because the go server did not set `grpc-encoding: identity`.

Compression negotiation should happen as if the header were present.

**Comment by edsko** [comment]
Closing this as WONTFIX, because we changed policy here: `identity` encoding is now _always_ allowed. We previously did not do this, with as rationale that if the client provided a specific lists of encodings that did not include `identity` we should respect that. However, we _anyway_ we have the option of deciding _per message_ whether to encode it or not, independent of the negotiated encoding algorithm.
